spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-204.railway.app:7138/railway
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create